### ISSUE TITLE
bug(ci): release workflow should be dependent on tests workflow success

### ISSUE THREAD

**Issue by allenthich** [allenthich/react-library-template#1]
## Issue: Make Release Workflow Dependent on Tests Workflow

**Description:**

Currently, the `Release` workflow (`release.yml`) and the `Tests` workflow (`tests.yml`) run independently. This means that a release can potentially be triggered even if the tests have failed, leading to the publication of potentially broken code.

To ensure higher quality releases, we should make the `Release` workflow dependent on the successful completion of the `Tests` workflow. This means the `Release` workflow should only run if the `Tests` workflow on the `main` branch has completed successfully.

**Proposed Solution:**

Modify the `Release` workflow (`release.yml`) to trigger only when the `Tests` workflow on the `main` branch has completed successfully. This can be achieved by adjusting the `workflow_run` trigger in the `release.yml` file.

**Current `release.yml` Trigger:**

```yaml
on:
  workflow_run:
    workflows: ['Tests']
    branches: [main]
    types:
      - completed
    # Add a check for success
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
```

**Acceptance Criteria:**

The Release workflow should only be triggered when the Tests workflow on the main branch has completed with a success status.
If the Tests workflow fails, the Release workflow should not be triggered.
The release.yml file should be updated to reflect the changes.
The workflow should be tested to ensure it works as expected.
